// Code generated by "stringer -type=IteratorType"; DO NOT EDIT.

package object

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NUMBER_ITER-0]
	_ = x[STRING_ITER-1]
	_ = x[BOOLEAN_ITER-2]
	_ = x[LIST_ITER-3]
	_ = x[MAP_ITER-4]
}

const _IteratorType_name = "NUMBER_ITERSTRING_ITERBOOLEAN_ITERLIST_ITERMAP_ITER"

var _IteratorType_index = [...]uint8{0, 11, 22, 34, 43, 51}

func (i IteratorType) String() string {
	if i < 0 || i >= IteratorType(len(_IteratorType_index)-1) {
		return "IteratorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IteratorType_name[_IteratorType_index[i]:_IteratorType_index[i+1]]
}
